# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b859818ed3e4a35f99cb65eaae0d921746addfae6bc60b882586bc047bb4b07f76019298960b8c6d651c62cbc7ce48eeecfa079046bf80ad719bfc5767e592c
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyC4ykQNuGC_ejZF6zXmJooypzhqccFdkbg") %>
  yelp_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "2ql6jImY-YsGzgNnAlEFJIcbYtnn9Oa_81V0BAkOkhmKO5z6crYfj42JsmNMGd1vrcdTPgWxChJLZJ5vVYU4pH7PYdYX_FpAKoacUN_D3royhUlyy6BB26kT07qbWnYx") %>

test:
  secret_key_base: 4005126c77d06ad06ab38cb21ebf3ebfcaef64f663bba051d6ba0776a5f36b462fc66a082ff4ddea5919a5d3ddd0a823483f18a42159f361ac4c726a6724386b
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyC4ykQNuGC_ejZF6zXmJooypzhqccFdkbg") %>
  yelp_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "2ql6jImY-YsGzgNnAlEFJIcbYtnn9Oa_81V0BAkOkhmKO5z6crYfj42JsmNMGd1vrcdTPgWxChJLZJ5vVYU4pH7PYdYX_FpAKoacUN_D3royhUlyy6BB26kT07qbWnYx") %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyC4ykQNuGC_ejZF6zXmJooypzhqccFdkbg") %>
  yelp_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "2ql6jImY-YsGzgNnAlEFJIcbYtnn9Oa_81V0BAkOkhmKO5z6crYfj42JsmNMGd1vrcdTPgWxChJLZJ5vVYU4pH7PYdYX_FpAKoacUN_D3royhUlyy6BB26kT07qbWnYx") %>
